### ISSUE TITLE
Plans for 3.x support?

### ISSUE THREAD

**Issue by sblommers** [xvik/guice-persist-orient#17] opened 2018-06-09 20:31 UTC
I was just wondering if a 3.x compatible release is planned.

**Comment by xvik** [comment] 2018-06-10 05:58
Yes, of course. I just have no time for it right now (just finished large generics-resolver update and working on dropwizard-guicey right now). I hope to work on persist-orient this summer but can't tell when (as soon as I finish with other things).

**Comment by kmhughes** [comment] 2019-06-17 21:31
I noticed that the master branch's build.gradle mentioned OrientDB 3.0.11, though about 7 tests failed. So is the master branch at least moving down the path of 3.x support?

If so, perhaps I will wait on the 3.x DB upgrade I was thinking of doing. If it is primarily tests that need to be completed, and I get to the point where I have some time, perhaps I can help with the test changes.

**Comment by xvik** [comment] 2019-06-18 02:44
Indeed, it's almost migrated to orient 3. The only remaining part is repositories support. There was an obvious need for more complex conversion support, then it was before and, last year, I started a little conversion framework, but it took much (much!) more time than I expected. Right now it is very close to completion, but I have to spend time now on dropwizard-guicey migration (before dropwizard 2.0 release).

So overall, orient 3.0 release is still planned, but I can't tell when it will be done for sure (as soon as I have time to finish everything)

**Comment by kmhughes** [comment] 2019-06-18 03:07
So if I don't use repositories support I should be OK? Just label my methods transactional and all will be fine?

It seemed like most tests passed, just a few didn't, so possibly the more simple parts I would want to use will work with raw OrientDB. And playing with my own code, it seems like it is working, though pooled transactional database connections seem deprecated, but I haven't founda replacement for them unless they have hidden that away. I will be probably browsing the code some. Seems they have not released javadoc on the 3.0.20 version, so I am building the project now. They are not the best in documenting things.

Good luck with the dropwizard-guicey release!

**Comment by xvik** [comment] 2019-06-18 03:22
Yes, everything except repositories should work (at least according to tests).

> pooled transactional database connections seem deprecated

What do you mean? 3.x branch use [ODatabasePool](https://github.com/xvik/guice-persist-orient/blob/master/src/main/java/ru/vyarus/guice/persist/orient/db/pool/DocumentPool.java#L50), which is a new api.

**Comment by kmhughes** [comment] 2019-06-18 04:30
Awesome on all working but repositories.

Cool about the pools. I'm slowly working my way through the new APIs, some I was using are now deprecated with suggestions in the code on how to do things now and I haven't traced through everything. I will work backwards from ODatabasePool. Thanks!

**Comment by xvik** [comment] 2019-06-18 04:38
If you're going to use the lib, you don't need to use pools yourself - it will be started automatically. And all connection types will use an underlying document connection from this pool. 

Changes from documented released version are mentioned in the [changelog](https://raw.githubusercontent.com/xvik/guice-persist-orient/master/CHANGELOG.md).
Most importantly, database connection objects were changed:
```
    - Bound connection objects changed:
        - Provider<OObjectDatabaseTx> -> Provider<ODatabaseObject>
        - Provider<ODatabaseDocumentTx> -> Provider<ODatabaseDocument>
```
And direct `OrienDB` object injection is now possible with `Provider<OrientDB>` (for manual connections)

**Comment by kmhughes** [comment] 2019-06-18 04:54
Perfect, thanks. Seems like an awesome library. Thanks for writing it. Will get the OSGi support in ASAP.

**Comment by kmhughes** [comment] 2019-07-06 12:56
I have started this project finally. I needed to get another project done
first which laid the groundwork for this.

Initial version is done, but I want to label some things optional from some
of your other libraries to see if it works. If not, I will label your other
libraries as well, it is about 5 lines in your Gradle file.

**Comment by kmhughes** [comment] 2019-07-11 15:47
Unfortunately I am not going to be able to take your project and make it
work with OSGi. Very sorry about that. I am going to clone it and keep the
pieces I can use, but unfortunately I cannot just make some changes I can
pass back to you.

The concern is that you make use of classes in the package
com.google.inject.internal. Without going into too many details, unless you
would like to understand the details, this breaks the OSGi model. Google
makes those internal packages private, which means they are not seen on the
OSGi classloader. You put some classes in that package to give access to
some package private methods, creating what is called a split package. The
dependencies at this point become unresolvable.

It is too bad Google didn't give a way of creating classes with access to
those package private methods or of getting the functionality they provide.

Thanks for the help you have given. I appreciate it!

**Comment by kmhughes** [comment] 2019-07-11 16:03
Actually I have one other idea to try. It leaves the split package in
place, which is unfortunately, but it may make it work. Will let you know.

**Comment by xvik** [comment] 2019-07-12 07:32
Guice internal package used in guice-ext-annotations to support abstract classes registration in guice (hack guice logic actually). This is required only for repositories part. And I agree that it is a bad thing (it will also stop me to properly migrate to java 11).

Actually, I already know how to workaround this, but, as usual, the problem is to find some time to rewrite it. I can only say that it's on my roadmap and eventually this will be fixed... someday

**Comment by kmhughes** [comment] 2019-07-12 15:30
I couldn't make it work, so am making mods to your code to strip out the
repository stuff. Too bad, your mixins looked like they would have been
very useful, but at this point, I need my code to move forward.

Should those changes you speak of ever happen, I will make the needed
changes, which were pretty easy, and switch over. Please reach out when you
complete everything and I will happily submit a patch.

**Comment by kmhughes** [comment] 2019-07-12 16:01
You can watch my changes here:
https://github.com/smartspaces-io/guice-persist-orient. I also cloned two
of the support projects since there are dependencies so I need them to use
OSGi.

**Comment by sblommers** [comment] 2019-10-28 14:07
I see that you are very busy with dropwizard-guice which is fantastic, we will switch to dropwizard very soon from restlet and custom stuffs, looks very promising.
I was wondering if the repositories stuff of guice-persist-orient is going to get some attention after the dropwizard support? I'm very eager to test OrientDB 3. :-)

Thanks for this incredible valuable library

**Comment by xvik** [comment] 2019-10-28 16:13
Yes, of course. I did not forget about it.
But don't expect it very soon.. most likely, only early next year. 

Guicey version is almost done (rc3 should be released this week), but then I'll need to finish object-converter, which will need new generics-resolver release (which is already prepared, but need to be validated). Generics-resolver must be also valiated with new guicey version which replace hk2 with guice in jersey (it is already partially done) to avoid breaking changes after release.

My personal goal is to finish converter this year, but I can't promise. Guice-persist will be developed together with converter and so should be released just after converter release.

**Comment by sblommers** [comment] 2019-10-28 16:28
Thanks!
I'll keep a close eye on your repositories.

**Comment by xvik** [comment] 2021-02-05 15:36
Sorry, I know you were waiting for so long (
I still want to finish the new version, but not sure when. Last year wasn't very productive.

**Comment by sblommers** [comment] 2021-02-05 16:08
Life happens :-) If something changes here be sure I'll jump on it to assist you in testing.

**Comment by sblommers** [comment] 2021-06-24 08:49
@xvik hi there, I have a small question. 

I naively pulled your code last night compiled 4.0.0-SNAPSHOT and started using it on my test projects with version 3.0.38 of orientdb with a plocal database, i didn't test remote (yet). 

10 unit tests failed while building (*.live repositories and 1 function ElVar test) so I skipped them. My test project uses around 100 repository interfaces all extending **ObjectCrud**. They all seem to work fine (??). I thougth that these repositories didn't work at all so I never tried it. Can you explain it? I didn't change a line of code in my implementations and I use modules like this;

`public class CheckPersist extends PrivateModule {

	@Override
	protected void configure() {
		final Cfg cfg = ConfigFactory.create(Cfg.class);
		
		Preconditions.checkNotNull(cfg.url());
		Preconditions.checkNotNull(cfg.username());	
		Preconditions.checkNotNull(cfg.password());
		
		install(new OrientModule(cfg.url(), cfg.username(), cfg.password()));
		install(new PackageSchemeModule(Transaction.class.getPackage().getName()));
		install(new RepositoryModule());
		install(new GeneratorAnchorModule());
		
		bind(DBInitializer.class).asEagerSingleton();
	}

	@Singleton
	static class DBInitializer {
		@Inject
		public DBInitializer(PersistService service) {
			service.start();
		}
	}
	
	@Provides @Exposed TransactionRepository transactionProvider(TransactionRepository ter) {
		return ter;
	}
	
	@Sources({"classpath:data.transactions.persist.properties" })
	interface Cfg extends Config {
		@Key("data.transactions.persist.url")
		String url();

		@Key("data.transactions.persist.username")
		String username();

		@Key("data.transactions.persist.password")
		String password();
	}
`

`@Transactional
@ProvidedBy(DynamicSingletonProvider.class)
public interface TransactionRepository extends ObjectCrud<Transaction> {
	@Query("select from Transaction")
	@DetachResult
	List<Transaction> allTransactions();
	
	@Query("select from Transaction")
	@DetachResult
	List<Transaction> transactions(@Skip int skip, @Limit int limit);
	
	@Query("select count(*) from Transaction")
	int count();
	
	@Query("select max(transactionID) from Transaction")
	long maxTransactionID();
}`

so nothing that special. I'll test a bit further. I was very suprised this works ... :-)

**Comment by xvik** [comment] 2021-06-24 09:27
@sblommers, hi!

Honestly, it's strange that almost everything is working :)
The only problem with the repositories now (as I remember) is lack of conversions in some cases:
orient now could return more types of response objects and the current converter would not be able to handle it.
It could also return different objects in some old cases... don't remember details now.

Also, as I remember, I did more refactorings but did not push it. 
I'll look at it this weekend, maybe I can do something quick and dirty (not optimal, but working)... 
Orient team already plan version 4 (i was afraid SAP would kill OSS part of it but seems its the opposite)

**Comment by xvik** [comment] 2021-06-26 10:04
Looked at the code.
Document API changed quite a lot in 3.0 introducing streams. I was refactoring on using only document API in repositories
which would greatly simplify workflow. But such an approach requires many supported conversions (object and graph objects do these conversions internally): document API always returns OResultSet which is converted to the required form. And that's why I was writing typed converter abstraction (and almost did actually).

You're lucky to use only object repositories: object connection works exactly as before.

I will try to do a simpler thing now: revert (for now) these refactorings and will try to just fix issues in the current implementation. Some features would be removed as you already have noted (not exists anymore in orient 3, or implemented differently).
Most likely, live and async queries would be removed too.

I also would upgrade to guice 5.

I hope it would not take much time and I could do it within about one week (don't have too much time for it, only a quick sprint).

If everything goes ok, then possibly I would be able to do such quick releases for 3.1 and 3.2. 
And someday I'll back to my initial plan and refactor repositories.

**Comment by sblommers** [comment] 2021-06-26 11:06
Hi there @xvik this would be so awesome. 

I only use objects indeed. A release with minimal but functional implementation would be very welcome. I have been using your library in production for over 4 years with great succes. I can very easily test our whole software stack (using well over 100 repository classes, mostly ObjectCrud).

:100:

**Comment by xvik** [comment] 2021-06-27 22:40
I pushed the required fixes, now tests pass. If possible, could you please check master with your tests?

In summary:
  - java 1.6 dropped (by orient)
  - nothing removed because of old api usage
  - updated to the latest orient 3.0.38 (and in this version FULLTEXT_HASH_INDEX was removed, so `@FullTextIndex` annotation was affected)
  - updated to guice 5.0.1

There are several issues, related to remote connection:
   - Function executed with object api might return a collection of nulls. Put descriptive exception for this case.
   - LIve query listener's unsubscribe method might not be called
   
Have to override default object connection class (object pool will return `OObjectDatabaseTxFixed` now) to workaround some result conversion (internal orient) bugs.

**Comment by sblommers** [comment] 2021-06-28 08:51
Hi there!  Very good news and love the update to guice 5
I hope I'll be able to test tonight / tomorrow, I have good hope all will turn out alright.
Thanks for spending your free time to do this. Much appreciated.

I'll get back here soon with results.
:wave:

**Comment by sblommers** [comment] 2021-06-29 20:41
The update to Guice 5 brought some dependency problems for me so I'm not able to replicate our production setup right now (probably this weekend/next week with some difficulties). I tested the repositories as single units of work using a remote connection and I touched most of our repository code and all seems to look pretty good and even a lot faster on queries (perhaps 2x). If I have more detailed results I'll post back. I have some stuff that needs to be finished by the end of this week.

Thanks for your latest updates!

**Comment by xvik** [comment] 2021-06-29 20:56
Thank you! Then I will release it in a few days (if there would be any problems I can always release a bugfix version).  

I briefly tried 3.1 and there were compilation problems (minimal, but still), so after release, I will try to update everything to 3.1 and if succeed release another version. 

If you want I can revert guice 5 upgrade and release this version with guice 4. It could be updated to guice 5 in the next 3.1 compatible version (if it would be possible).

**Comment by sblommers** [comment] 2021-06-29 21:05
It's best to release it with guice 5 even if is is for pushing next-gen. I need to upgrade my code to 5 anyway. If it won't work for me I'll make a snapshot/minor with guice 4 until I succeed my upgrade path. Thanks @xvik looking forward to using a fresh baked release :-)

:+1:

**Comment by xvik** [comment] 2021-07-03 21:19
[Released](https://github.com/xvik/guice-persist-orient/releases/tag/4.0.0)

[Release notes](http://xvik.github.io/guice-persist-orient/4.0.0/about/release-notes/)

[Examples](https://github.com/xvik/guice-persist-orient-examples) updated

**Comment by sblommers** [comment] 2021-07-04 08:28
Awesome! Thank for your hard work. First l need to rework these old libraries to get Guice 5 in (it's a bit of a pain but needs to be done).  I'll do a full system test and report back to you. I'll create a statistics report on some really big datasets (250GB and growing on about 100 clusters). (OrientDB 2.2 vs 3.0 comparison).

**Comment by xvik** [comment] 2021-07-04 11:36
Upgraded master to orient 3.1: all tests pass. I Will check few things and release a new version soon (4.1.0).

**Comment by xvik** [comment] 2021-07-04 19:41
3.1 compatible version [released](https://github.com/xvik/guice-persist-orient/releases/tag/4.1.0)

[Release notes](http://xvik.github.io/guice-persist-orient/4.1.0/about/release-notes/)

Actually no changes except compatibility fixes

**Comment by xvik** [comment] 2021-07-05 19:49
In 3.2.0 the main changes are [not creating default users by default and graalvm usage instead of nashorn](https://orientdb.org/docs/3.2.x/release/3.2/What-is-new-in-OrientDB-3.2.html)

With reverted legacy behaviour:

```java
OGlobalConfiguration.SCRIPT_POLYGLOT_USE_GRAAL.setValue(false)
OGlobalConfiguration.CREATE_DEFAULT_USERS.setValue(true)
```

All tests pass. So basically there should be no problems for you to try it (no incompatibilities).

Ideally, I should update auto db creation methods to automatically create users. But this is useful mostly for tests (not a very major thing). For now, just updated master to 3.2 to show compatibility.

**Comment by xvik** [comment] 2021-09-14 05:01
@sblommers did you face any problems during migration? Just curious how it goes (and worry that might be not well)

**Comment by sblommers** [comment] 2021-09-14 09:27
Hi there @xvik I realized I never got back here and got extremely side-tracked due to work, holiday (finally) and moving to another city. I'm done reworking our stack and able to test these newer versions hopefully at the end of this week or perhaps this weekend. I did try out a bunch of unit tests that worked flawlessly. I'll get back to you soon.

Offtopic: I noticed ArcadeDB ... seems interesting :-)

**Comment by xvik** [comment] 2021-09-14 09:37
Glad to hear) 
I'm looking at ArcadeDB too (watching) :) Looks interesting, but probably will not be released soon (too early stage)

**Comment by sblommers** [comment] 2021-09-20 09:49
I do have everything working as it should but no statistics yet (work is pushing me around). There are some queries I hoped were a bit faster (using indexes on sum or max for example but they seem not yet fixed yet in any orientdb version) but this lib does it's work well. I'm currently trying to get some statistics out of it because some versions perform quite a bit better or use less ram/cpu but it's all related to the orient-db-server.

I'm sure we can close this issue when you like because all seem to work fine on the object/document level.
I'll post any usefull statistics soon but I guess most users pick the most latest version of orientdb (which in my opinion is not that much of an upgrade yet).

https://github.com/orientechnologies/orientdb/issues/2655

**Comment by xvik** [comment] 2021-09-20 10:05
Thank you for the info! 
Agree, it could be closed now to not confuse anyone. 

It would be very interesting to see real statistics (in comparison)!

**Closed** 2021-09-20 10:08 UTC
Labels: enhancement
